apiVersion: v1
kind: Service
metadata:
  name: bonus_database
  labels:
    app: db-aliases
spec:
  selector:
    app: bonusdb
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: flight_database
  labels:
    app: db-aliases
spec:
  selector:
    app: flightdb
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: ticket_database
  labels:
    app: db-aliases
spec:
  selector:
    app: ticketdb
  ports:
  - port: 5432
    targetPort: 5432apiVersion: v1
kind: Service
metadata:
  name: bonus_database
  labels:
    app: db-aliases
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: bonusdb
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: flight_database
  labels:
    app: db-aliases
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: flightdb
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ticket_database
  labels:
    app: db-aliases
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  selector:
    app: ticketdb
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  type: ClusterIP